### ISSUE TITLE
Quick Question - Operating Systems PRE 10.11?

### ISSUE THREAD

**Issue by mattdrepo** [robbertkl/ResolutionMenu#5]
Quick Question - Resolution Menu App - Can it be built for systems Pre 10.11 ? It would be great if you could go back to operating systems as far as 10.6.8.  Anyway, I await some feedback as to this request and thank you for the hard work in the meantime!

**Comment by robbertkl** [comment]
Yeah, it probably can, but not sure exactly which APIs it's using. You should be able to just download and run the project with XCode. Looking at the commit history, it seems I've created it end of 2013, which was when Mavericks (10.9) was out, so that should work. Not sure about Snow Leopard, because it was released before the "MacBook Pro with Retina display" was released, which might have triggered the introduction of HiDPI support on OS X.
