### ISSUE TITLE
Cluttered menu on non-HiDPI external displays with HiDPI options

### ISSUE THREAD

**Issue by iemg** [robbertkl/ResolutionMenu#7]
I tested it with a non-HiDPI external display, which yields following strange list of options:
<img width="184" alt="Bildschirm­foto 2023-02-19 um 16 12 37" src="https://user-images.githubusercontent.com/9716564/219956887-8a91a8d0-098c-4d3c-87a0-8a76ea5d7b94.png">

Apart from that resolution change works without problems. I will still reopen that because the menu is cluttered, but it's not a critical bug.

_Originally posted by @iemg in https://github.com/robbertkl/ResolutionMenu/issues/6#issuecomment-1436014634_

(forgot, that as an non collaborator I can't reopen issues if I didn't close them myself :))

**Comment by robbertkl** [comment]
Hi, thanks for reporting. I'm not sure this is an actual issue, as this is apparently the list of available display resolutions communicated by the device / the OS. I do agree it's a bit of a strange list: I would expect if 1920x1080 is the max resolution (the display's native resolution), that 960x540 HiDPI would be the max HiDPI resolution, or maybe slightly higher because of the upscaling macOS can do (the "more space" settings in System Preferences).

**Comment by iemg** [comment]
Yes, I remember from my old MacBook Air (11") that ResolutionMenu would offer all possibilities which are way more than System Preferences would offer, but the doubled non-HiDPI and HiDPI are still strange.

Just for reference, System Preferences yields that:

<img width="545" alt="Bildschirm­foto 2023-02-19 um 21 57 09" src="https://user-images.githubusercontent.com/9716564/219974723-58939974-6c6a-4cff-aebe-975d436fa887.png">

So from my side it's also ok to close this issue, still, there's something :D

**Comment by robbertkl** [comment]
OK, will close it for now.

Since it's the list the OS is reporting, I guess the only way is to do some "smart" filtering to dismiss resolutions that seem incorrect, but I feel that's a bit risky to do, since it might take out perfectly good options for some people/cases.
