### ISSUE TITLE
Lack of sharpness when scaling to 2560x1440 resolution on a monitor with native 1920x1080 max resolution

### ISSUE THREAD

**Issue by davidmickelsen** [robbertkl/ResolutionMenu#9]
Thanks for the great app. I'm very happy to have found a solution that will simulate a 2560x1440 resolution on my display. However, when selecting this resolution on my natively 1920x1080 max resolution monitor, the sharpness of the display is affected somewhat. I know this is to be expected when simulating a resolution higher than a display natively supports; but I wanted to ask in here if the developers or community have any ideas to improve this sharpness issue at all.

Thanks.

**Comment by robbertkl** [comment]
Hi 👋🏻, I don't think there's much we can do about it. It's macOS that scales it a certain way, and going up these steps is missing a lot of pixels. Usually, with HiDPI (retina / @2x) resolutions, you won't really notice it because HiDPI is already very sharp.

In your case, that would mean a native resolution of "960x540 (HiDPI)", which you can run scaled as "1280x720 (HiDPI)", which might not visibly lose too much sharpness. However, that won't give you much screen real estate, HiDPI is more suited for 4k/5k monitors with a high pixel density. Unfortunately, non-HiDPI resolutions will lose sharpness very quickly.

**Comment by davidmickelsen** [comment]
Understood. Thanks for the reply, Robbert.
